import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import LogInButton from "./_components/LogInButton";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const HEADER_LINKS = [{
  path: '/home',
  text: 'Home'
},
{
  path: '/products',
  text: 'Products'
},
{
  path: '/about',
  text: 'About'
},
{
  path: '/register',
  text: 'Sign up'
},
{
  path: '/login',
  component: <LogInButton />
}]

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header>
          {
            HEADER_LINKS.map((link, index) => {
              return link.text ?
              <Link key={index} href={link.path}>{link.text}</Link> :
              <Link key={index} href={link.path}>{
                link.component
              }</Link>
            })
          }
        </header>
        <main>
          {children}
        </main>
        <footer>
          &copy; 2026 | fake store api website
        </footer>

      </body>
    </html>
  );
}
